name: CI

on: [push, pull_request]

jobs:
  build:
    name: ${{ matrix.os.windows_environment == '' && matrix.os.name || format('windows/{0}', matrix.os.windows_environment) }} - OCaml ${{ matrix.ocaml-version }}

    strategy:
      fail-fast: false
      # Test Linux, macOS and Windows with the oldest, LTS, and newest supported
      # OCaml versions.
      matrix:
        os:
          - name: macos-latest
          - name: ubuntu-latest
          - name: windows-latest
            windows_environment: cygwin
          - name: windows-latest
            windows_environment: msys2
        ocaml-version:
          - "4.14"
          - "5.4"
        include:
          - os:
              name: ubuntu-latest
            ocaml-version: "3.08"

    runs-on: ${{ matrix.os.name }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set-up OCaml ${{ matrix.ocaml-version }}
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: ${{ matrix.ocaml-version }}
          windows-environment: ${{ matrix.os.windows_environment == '' && 'cygwin' || matrix.os.windows_environment }}

      # Check building with make
      - run: |
          opam exec -- ${{ runner.os == 'Windows' && 'sh ' || '' }}./configure
          opam exec -- make all opt

      # Check installing with opam
      - run: opam pin add ocamlfind .

      # Test it
      - run: opam exec -- ocamlfind list
      - run: opam exec -- ocaml .github/workflows/toplist.ml
