name: CI

on: [push, pull_request]

jobs:
  build:
    name: ${{ matrix.os }} - OCaml ${{ matrix.ocaml-version }}

    strategy:
      fail-fast: false
      # Test Linux, macOS and Windows with the oldest, LTS, and newest supported
      # OCaml versions.
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
        ocaml-version:
          - "4.14"
          - "5.4"
        include:
          - os: ubuntu-latest
            ocaml-version: "3.08"

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set-up OCaml ${{ matrix.ocaml-version }}
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: ${{ matrix.ocaml-version }}

      # Check building with make
      - run: |
          opam exec -- ${{ runner.os == 'Windows' && 'sh ' || '' }}./configure
          opam exec -- make all opt

      # Temporarily - allow --strict to work
      - run: opam repo add --all strict git+https://github.com/dra27/opam-repository.git#fix-strict

      # Check installing with opam
      - run: opam pin add ocamlfind . --strict

      # Test it
      - run: opam exec -- ocamlfind list
      - run: opam exec -- ocaml .github/workflows/toplist.ml
